export const FETCH_POST_START = Symbol('FETCH_POST_START');
export const FILTER_PROJECTS = Symbol('FILTER_PROJECTS');
export const PROJECTSLIST_START = Symbol('PROJECTSLIST_START');
export const PROJECTSLIST_SUCCESS = Symbol('PROJECTSLIST_SUCCESS');
export const PROJECTSLIST_FAILURE = Symbol('PROJECTSLIST_FAILURE');
export const DELTET_PROJECT_START = Symbol('DELTET_PROJECT_START');
export const DELTET_PROJECT_FAIL = Symbol('DELTET_PROJECT_FAIL');
export const DELTET_PROJECT_SUCCESS = Symbol('DELTET_PROJECT_SUCCESS');
